### ISSUE TITLE
Mission Generation on other HDD

### ISSUE THREAD

**Issue by launchpad4life** [shdwp/dcs_liberation#1]
As I am using my D: drive for my Saved Games folder, the program is unable to generate the Mission.
[Errno 2] No such file or directory: 'C:\\Users\\*NAME*\\Saved Games\\DCS\\liberation_save_tmp'
I'd love to select a specific path where the file is generated.

**Comment by shdwp** [comment]
I've supposedly fixed this in 1.12, could you please check it and report whether it's actually working or not?

**Comment by launchpad4life** [comment]
Sorry for the late answer.
Unfortunately it still doesnt work.
I attached the log.txt
[logs.txt](https://github.com/shdwp/dcs_liberation/files/2167458/logs.txt)

**Comment by shdwp** [comment]
You could settle for a workaround at the time until I find a way to reliably and dependencyless find the correct way by myself.

Open the `start.bat` file and change `%UserProfile%` to the **parent** folder of you Saved Games folder:

`py.exe __init__.py "D:\Docs" > logs.txt 2>&1`

In this example the resulting path would be *D:\Docs\Saved Games*

**Comment by launchpad4life** [comment]
Unfortunately it still points to the C drive path with the change you suggested.
I also tried linking the `Saved Games` folder into my C: user directory, but that didnt work either.

**Comment by shdwp** [comment]
It couldn't. Please check whether you have the latest release and paste the contents here for me to verify the syntax.

**Comment by launchpad4life** [comment]
`py.exe __init__.py "D:\Benutzer\*myusername* > logs.txt 2>&1`
Am on version 1.12

**Comment by shdwp** [comment]
So, your DCS directory should be at `D:\Benutzer\*username*\Saved Games\DCS`?

**Comment by launchpad4life** [comment]
That's correct.

**Comment by shdwp** [comment]
If you are really using the latest release there couldn't be anything wrong. Care to share the logs.txt?

**Comment by launchpad4life** [comment]
Here you go, tried it with 1.13_rc3.
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "D:\Benutzer\USERNAME\Downloads\DCS Mods\dcs_liberation_1.13_rc3\ui\eventmenu.py", line 225, in start
    self.game.initiate_event(self.event)
  File "D:\Benutzer\USERNAME\Downloads\DCS Mods\dcs_liberation_1.13_rc3\game\game.py", line 197, in initiate_event
    event.generate()
  File "D:\Benutzer\USERNAME\Downloads\DCS Mods\dcs_liberation_1.13_rc3\game\event\event.py", line 56, in generate
    self.operation.mission.save(persistency.mission_path_for("liberation_nextturn.miz"))
  File "D:\Benutzer\USERNAME\Downloads\DCS Mods\dcs_liberation_1.13_rc3\dcs\mission.py", line 1800, in save
    with zipfile.ZipFile(filename, 'w', compression=zipfile.ZIP_DEFLATED) as zipf:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\zipfile.py", line 1090, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\Saved Games\\DCS\\Missions\\liberation_nextturn.miz'
Al Maktoum - T-80UD 4
Al Maktoum - T-55 4
Al Maktoum - BTR-80 4
Al Maktoum - C-101CC 2
Al Maktoum - F-5E-3 2
Al Maktoum - MiG-21Bis 2
Al Maktoum - Su-25T 1
Al Maktoum - L-39ZA 1
Al Maktoum - MiG-15bis 1
Al Maktoum - Ural-375 ZU-23 1
Al Minhad - T-80UD 4
Al Minhad - T-55 4
Al Minhad - BTR-80 4
Al Minhad - C-101CC 2
Al Minhad - F-5E-3 2
Al Minhad - MiG-21Bis 2
Al Minhad - Su-25T 1
Al Minhad - L-39ZA 1
Al Minhad - MiG-15bis 1
Al Minhad - Ural-375 ZU-23 1
Dubai Intl - T-80UD 6
Dubai Intl - T-55 6
Dubai Intl - BTR-80 6
Dubai Intl - T-90 6
Dubai Intl - MiG-29S 4
Dubai Intl - MiG-29A 4
Dubai Intl - Su-33 4
Dubai Intl - Su-27 4
Dubai Intl - Ka-50 2
Dubai Intl - Su-34 2
Dubai Intl - Su-25 2
Dubai Intl - Su-25T 2
Dubai Intl - Osa 9A33 ln 1
Dubai Intl - 2S6 Tunguska 1
Dubai Intl - Ural-375 ZU-23 1
Sharjah Intl - T-80UD 6
Sharjah Intl - BTR-80 6
Sharjah Intl - T-90 6
Sharjah Intl - M-2000C 4
Sharjah Intl - MiG-29A 4
Sharjah Intl - Su-27 4
Sharjah Intl - Ka-50 2
Sharjah Intl - Su-34 2
Sharjah Intl - Su-25 2
Sharjah Intl - Osa 9A33 ln 1
Sharjah Intl - 2S6 Tunguska 1
Fujairah Intl - T-80UD 6
Fujairah Intl - T-55 6
Fujairah Intl - BTR-80 6
Fujairah Intl - T-90 6
Fujairah Intl - MiG-29S 4
Fujairah Intl - MiG-29A 4
Fujairah Intl - Su-33 4
Fujairah Intl - Su-27 4
Fujairah Intl - Ka-50 2
Fujairah Intl - Su-34 2
Fujairah Intl - Su-25 2
Fujairah Intl - Su-25T 2
Fujairah Intl - Osa 9A33 ln 1
Fujairah Intl - 2S6 Tunguska 1
Fujairah Intl - Ural-375 ZU-23 1
Khasab - T-80UD 6
Khasab - T-55 6
Khasab - BTR-80 6
Khasab - T-90 6
Khasab - MiG-29S 4
Khasab - MiG-29A 4
Khasab - Su-33 4
Khasab - Su-27 4
Khasab - Ka-50 2
Khasab - Su-34 2
Khasab - Su-25 2
Khasab - Su-25T 2
Khasab - Osa 9A33 ln 1
Khasab - 2S6 Tunguska 1
Khasab - Ural-375 ZU-23 1
Sir Abu - T-80UD 5
Sir Abu - BTR-80 5
Sir Abu - T-90 5
Sir Abu - AJS37 3
Sir Abu - C-101CC 3
Sir Abu - M-2000C 3
Sir Abu - Ka-50 1
Sir Abu - L-39ZA 1
Sir Abu - Su-25T 1
Sir Abu - Osa 9A33 ln 1
Sir Abu - Ural-375 ZU-23 1
Sirri Island - T-80UD 6
Sirri Island - BTR-80 6
Sirri Island - T-90 6
Sirri Island - M-2000C 4
Sirri Island - MiG-29A 4
Sirri Island - Su-27 4
Sirri Island - Ka-50 2
Sirri Island - Su-34 2
Sirri Island - Su-25 2
Sirri Island - Osa 9A33 ln 1
Sirri Island - 2S6 Tunguska 1
Abu Musa - T-80UD 4
Abu Musa - T-55 4
Abu Musa - BTR-80 4
Abu Musa - C-101CC 2
Abu Musa - F-5E-3 2
Abu Musa - MiG-21Bis 2
Abu Musa - Su-25T 1
Abu Musa - L-39ZA 1
Abu Musa - MiG-15bis 1
Abu Musa - Ural-375 ZU-23 1
Tunb Kochak - T-80UD 6
Tunb Kochak - T-55 6
Tunb Kochak - BTR-80 6
Tunb Kochak - T-90 6
Tunb Kochak - MiG-29S 4
Tunb Kochak - MiG-29A 4
Tunb Kochak - Su-33 4
Tunb Kochak - Su-27 4
Tunb Kochak - Ka-50 2
Tunb Kochak - Su-34 2
Tunb Kochak - Su-25 2
Tunb Kochak - Su-25T 2
Tunb Kochak - Osa 9A33 ln 1
Tunb Kochak - 2S6 Tunguska 1
Tunb Kochak - Ural-375 ZU-23 1
Tunb Island - T-80UD 5
Tunb Island - BTR-80 5
Tunb Island - T-90 5
Tunb Island - AJS37 3
Tunb Island - C-101CC 3
Tunb Island - M-2000C 3
Tunb Island - Ka-50 1
Tunb Island - L-39ZA 1
Tunb Island - Su-25T 1
Tunb Island - Osa 9A33 ln 1
Tunb Island - Ural-375 ZU-23 1
Bandar Lengeh - T-80UD 6
Bandar Lengeh - T-55 6
Bandar Lengeh - BTR-80 6
Bandar Lengeh - T-90 6
Bandar Lengeh - MiG-29S 4
Bandar Lengeh - MiG-29A 4
Bandar Lengeh - Su-33 4
Bandar Lengeh - Su-27 4
Bandar Lengeh - Ka-50 2
Bandar Lengeh - Su-34 2
Bandar Lengeh - Su-25 2
Bandar Lengeh - Su-25T 2
Bandar Lengeh - Osa 9A33 ln 1
Bandar Lengeh - 2S6 Tunguska 1
Bandar Lengeh - Ural-375 ZU-23 1
Qeshm Island - T-80UD 5
Qeshm Island - BTR-80 5
Qeshm Island - T-90 5
Qeshm Island - AJS37 3
Qeshm Island - C-101CC 3
Qeshm Island - M-2000C 3
Qeshm Island - Ka-50 1
Qeshm Island - L-39ZA 1
Qeshm Island - Su-25T 1
Qeshm Island - Osa 9A33 ln 1
Qeshm Island - Ural-375 ZU-23 1
Havadarya - T-80UD 6
Havadarya - T-55 6
Havadarya - BTR-80 6
Havadarya - T-90 6
Havadarya - MiG-29S 4
Havadarya - MiG-29A 4
Havadarya - Su-33 4
Havadarya - Su-27 4
Havadarya - Ka-50 2
Havadarya - Su-34 2
Havadarya - Su-25 2
Havadarya - Su-25T 2
Havadarya - Osa 9A33 ln 1
Havadarya - 2S6 Tunguska 1
Havadarya - Ural-375 ZU-23 1
Bandar Abbas - T-80UD 6
Bandar Abbas - T-55 6
Bandar Abbas - BTR-80 6
Bandar Abbas - T-90 6
Bandar Abbas - MiG-29S 4
Bandar Abbas - MiG-29A 4
Bandar Abbas - Su-33 4
Bandar Abbas - Su-27 4
Bandar Abbas - Ka-50 2
Bandar Abbas - Su-34 2
Bandar Abbas - Su-25 2
Bandar Abbas - Su-25T 2
Bandar Abbas - Osa 9A33 ln 1
Bandar Abbas - 2S6 Tunguska 1
Bandar Abbas - Ural-375 ZU-23 1
Lar Airbase - T-80UD 6
Lar Airbase - T-55 6
Lar Airbase - BTR-80 6
Lar Airbase - T-90 6
Lar Airbase - MiG-29S 4
Lar Airbase - MiG-29A 4
Lar Airbase - Su-33 4
Lar Airbase - Su-27 4
Lar Airbase - Ka-50 2
Lar Airbase - Su-34 2
Lar Airbase - Su-25 2
Lar Airbase - Su-25T 2
Lar Airbase - Osa 9A33 ln 1
Lar Airbase - 2S6 Tunguska 1
Lar Airbase - Ural-375 ZU-23 1
[Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\Saved Games\\DCS\\liberation_save_tmp'
[Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\Saved Games\\DCS\\liberation_save_tmp'
[Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\Saved Games\\DCS\\liberation_save_tmp'
<theater.base.Base object at 0x0000000004064FD0> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.M_2000C'>: 3, <class 'dcs.planes.AJS37'>: 3}
<theater.base.Base object at 0x0000000004064FD0> for <class 'dcs.task.CAS'> (0): {<class 'dcs.helicopters.Ka_50'>: 1, <class 'dcs.planes.Su_25T'>: 1}
<theater.base.Base object at 0x0000000004064FD0> for <class 'dcs.vehicles.AirDefence'> (0): {<class 'dcs.vehicles.AirDefence.SAM_SA_8_Osa_9A33'>: 1, <class 'dcs.vehicles.AirDefence.AAA_ZU_23_on_Ural_375'>: 1}
generated weather 4
`

**Comment by shdwp** [comment]
Thanks, could you please try this release: https://github.com/shdwp/dcs_liberation/releases/tag/1.13_rc4

**Comment by launchpad4life** [comment]
Awesome, that worked! Well done, very much appreciated. Keep up the good work!
