### ISSUE TITLE
Recommendation: Add static aircraft to prevent microstutter at WP3 trigger

### ISSUE THREAD

**Issue by HomeFries94** [shdwp/dcs_liberation#10]
Currently, the mission stutters when the client approaches within the WP3 trigger zone and the enemy units are spawned (this is also mentioned in the manual).  A good workaround for this is to create duplicates of these objects at an airfield away from the fight so that they are loaded at the mission start and don't cause a microstutter (or at least minimize the microstutter) when the client enters the WP3 trigger zone.

For example, if it is an intercept mission and REDFOR spawns in 2 F-5Es and 1 Il-78 near Tonopah, add an F-5E and an Il-78 as static objects at Nellis so that the objects are already in memory when the mission starts.

**Comment by shdwp** [comment]
Good suggestion, thanks!

**Comment by shdwp** [comment]
Scheduled for next release.
