### ISSUE TITLE
"Enemy Attacking" aircraft selections

### ISSUE THREAD

**Issue by MaHuJa** [shdwp/dcs_liberation#11]
![image](https://user-images.githubusercontent.com/3055693/43684480-3163557e-98a1-11e8-812f-77aa9ae52d3d.png)
![image](https://user-images.githubusercontent.com/3055693/43684486-49e6ece6-98a1-11e8-84d6-eaaa9b627583.png)
![image](https://user-images.githubusercontent.com/3055693/43684503-b5182c00-98a1-11e8-911e-3e362a09fb90.png)

On that base, I have 8x F-18 now sitting idle. 

The aircraft limits in place seem reasonable for attacking, not defending, in this mission type.
Naval strike and AA strike are both affected by this.

**Comment by shdwp** [comment]
Should be fixed in 1.4.
