### ISSUE TITLE
Ground units can spawn in lake

### ISSUE THREAD

**Issue by Khopa** [shdwp/dcs_liberation#13]
The issue occured on a frontline mission between Maykop and Krasnodar on Caucasus map : 

![image](https://user-images.githubusercontent.com/2546901/43900959-86c2f11c-9be6-11e8-9478-8e5c8de481ed.png)

Because of the presence of a big lake near Krasnodar, some ground units spawned inside the lake : 

![image](https://user-images.githubusercontent.com/2546901/43900971-8c6b9bfa-9be6-11e8-875e-1b14b4bdfd61.png)

![image](https://user-images.githubusercontent.com/2546901/43900984-92d1c910-9be6-11e8-8806-8bafb450163d.png)

![image](https://user-images.githubusercontent.com/2546901/43901258-58f0e108-9be7-11e8-936b-73c4e759b740.png)

**Possible ways to fix this :**

* A (tedious) way to resolve the issue would be to reference the existing lakes on each map as polygons, then when generating unit positions on the frontline, make sure that they are not inside one of referenced lake, and find another spot to place the unit if necessary.

* When trying to move a unit that has been generated in the water in the DCS editor, then the unit is put on the shore automatically.  Maybe there is a way to trigger such behaviour with pydcs ?

**Comment by Khopa** [comment]
Fixed it here for Caucasus : https://github.com/Khopa/dcs_liberation/commit/feb37d916aba3773ce1ebeb2b35dadf488223cac

I modified the cau_terrain.miz file, and added new polygons (symbolized by Russian A-50 groups). Then modified the generate_landmap.py to extract the list of 'lakes', and then pickle-dump them in a 'lakemap.p' file.

**Example :** 

![image](https://user-images.githubusercontent.com/2546901/43969383-439c79dc-9cca-11e8-9866-d81c32b7ac82.png)

Then using the already available ray_tracing function, i check if the generated position are inside the known lakes. If it's in a lake, a new position is randomized, until a valid one is found. 

 And it works 😏    

**Before :**

![image](https://user-images.githubusercontent.com/2546901/43970119-c33b437e-9ccc-11e8-8ab3-7403bdfebf23.png)

**After :** 

![image](https://user-images.githubusercontent.com/2546901/43970122-c82abad6-9ccc-11e8-8491-57419b63e719.png)

I don't have PG and/or Nevada installed right now so the "lake" map is only for Caucasus right now.

**Another idea :** 

It could be smart to take advantage of this "lakemap" feature to force the ground conflict to take place inside valleys between Soganlung and Beslan, or also to avoid spawning units inside dense forest where CAS has no chance to find them...

**Comment by shdwp** [comment]
Thanks a lot for the suggestions, I really like the idea of using this to also avoid the mountains. Although I'd rather simply add the support to the existing landmap to avoid code duplication. I'll look into this further when I'll have time.

**Comment by MaHuJa** [comment]
For the mountains I would suggest simply raising their altitudes when they do, rather than prohibiting mountain overflight entirely.

Then you have the coast. 

Attached is a mission doing a base attack from Sochi to Gelendzhik. Friendly units start IN the bay.
[liberation_nextturn.zip](https://github.com/shdwp/dcs_liberation/files/2282896/liberation_nextturn.zip)
(Renamed file)

(Before flying, note how no planes start with a loadout.)

FWIW When the logs were parsed, the result was a "mission failure" after air assets struck 3 ground units, and then the base was captured anyway.

**Comment by Khopa** [comment]
> For the mountains I would suggest simply raising their altitudes when they do, rather than prohibiting mountain overflight entirely.

My solution does not forbid mountain overflight, it is only for ground units spawn. (to avoid spawning a T90 on a 50 degree slope for instance, or on the summit of a mountain it could never have reached). 

But now that you mention, spawning aircraft over moutain probably cause issues too for quick mission, i haven't encountered this yet.

> Friendly units start IN the bay.

Indeed...

![image](https://user-images.githubusercontent.com/2546901/44044350-9f336af0-9f25-11e8-8a59-de2f3e92a8ce.png)

The bay is not accounted for in the terrain polygon in the [current miz](https://github.com/shdwp/dcs_liberation/blob/master/resources/tools/cau_terrain.miz) file that serve as reference for units spawning.

![image](https://user-images.githubusercontent.com/2546901/44043788-00e2e9ee-9f24-11e8-91f7-1ab60d3f0019.png)

If fixed the poly in my dev branch. I know it's used for the frontline mission generator, however, i'm not sure if the base attack mission actually use it to generate the ground units' position. I don't know how it would behave if there was no available position for spawning ground units; it would probably fail to generate the mission.. 

A solution to fix this could be to add a value for the final base attack direction (for each base, or only for those who need it to be overidden), so the airbase attack generator would be able to place the units on a proper 'land' spot.

> Before flying, note how no planes start with a loadout.

Are you running from the sources or from the release ?

I had the same issue running from source, cause it does not embed the .lua payload files. You have to copy them from the release version to your current copy of the repository. (see ./resources/payloads). I don't think the readme mention it and it took me an hour to figure out, and this indeed an issue !

**Comment by shdwp** [comment]
There's two rules regarding ground units placement - `is_on_land`, which check for landmap, and control point `radials`, which is older system, from which direction of the base attack is calculated (so that it would always be on land).

**Comment by shdwp** [comment]
Lakes getting in the way of frontline-type missions will be fixed in next version, other types of missions still need testing.

**Comment by shdwp** [comment]
This case is fixed in 1.4.
