### ISSUE TITLE
The map is hard to read / text overlaps

### ISSUE THREAD

**Issue by Khopa** [shdwp/dcs_liberation#14]
Because the map is too small, a lot of spots are hard to read :

**Example :**

![image](https://user-images.githubusercontent.com/2546901/44045555-25228382-9f29-11e8-8ff4-afb0deb0cb5f.png)

I tried scaling the background image and the reference points to get a bigger map : 

![image](https://user-images.githubusercontent.com/2546901/44045585-3dc10dc8-9f29-11e8-92d6-324e4e334e48.png)

It's a bit better, but even then, text is still overlapping.

In the long term, it would be better to have a zoomable map, however, i doubt Tkinter would allow it to be implemented smoothly.

**Comment by shdwp** [comment]
Your PR is merged, so it's a little bit better now.
