### ISSUE TITLE
Feature Request: Be able to move units across base

### ISSUE THREAD

**Issue by Khopa** [shdwp/dcs_liberation#15]
Currently it is really frustrating for the player that after investing a lot of money in one base, he is not able to use the assets he deployed there anymore, once this base is no more located near a frontline. 

In this example i have 100+ units that can't be used anymore at Maykop : 

![image](https://user-images.githubusercontent.com/2546901/44087417-0ed54d5c-9fc0-11e8-97f3-4bfd3c3658c1.png)

It should be possible to redeploy units from one base to another, which would make them unavailable for a turn (or more) while they are being moved.

This will require a bit of work on the UI though.

**Comment by shdwp** [comment]
You can sell the units on one base and buy them on another.
