### ISSUE TITLE
Patriot SAM sites are incorrectly generated

### ISSUE THREAD

**Issue by Khopa** [shdwp/dcs_liberation#16]
**Issue :** The Patriot SAM sites are not functionnal. 

***

In this example, on Soganlung airbase, for air defense, i have 1 Vulcan AAA, 1 Avenger, and 2 Patriot

![image](https://user-images.githubusercontent.com/2546901/44088652-43ab9e88-9fc4-11e8-9c8f-1ab643ea243e.png)

When i decide to counter an ennemy AA Strike mission (But i believe it is the same for all missions)

![image](https://user-images.githubusercontent.com/2546901/44088736-88c5eb90-9fc4-11e8-9930-9d0438de8e9c.png)

When a Patriot site is generated, it is made of only one unit, which a "Patriot ICC". This result in an non-functionnal Patriot site : 

![image](https://user-images.githubusercontent.com/2546901/44090093-49b08046-9fc9-11e8-9e1c-bbf9f2e67b4a.png)

For the Patriot SAM site to be functionnal in the DCS engine, it needs to be a group made of at least : 

| Unit | Role |
| -----  | ---- |
| Patriot AN/MRC 137 | Radio communications
| Patriot  AN/MPQ-53 | Search & Illumination radar
| Patriot AN/MSQ-104 | Command center
| Patriot LN/M901 | Missile Launcher
| Patriot ICC | (?)
| Patriot EPP-III | (?)

As demonstrated by the editor's template : 

![image](https://user-images.githubusercontent.com/2546901/44089756-3fe3abe8-9fc8-11e8-9755-06b62811c845.png)

***

**Short term workaround :** remove the Patriot sites for Blue side (Red side does not have any equivalent asset enabled right now, so it's good for balance too)

**Mid term solution :** generate proper groups for SAM that require multiple units to be functionnal

For the debriefing/results calculations, the destruction of the radar of the Patriot site could account for the destruction of the site ?  (Cause it is targetable by SEAD/DEAD aircraft with anti-radiations missiles, and probably represent the most valuable asset of the site)

**Comment by shdwp** [comment]
Thanks, I've missed that. Could you maybe propose a better AA units for both sides? 1 AAA, 2-3 SAMS with progression from worse to better.

**Comment by shdwp** [comment]
In any case I'll remove the patriots from the next release anyway.

**Comment by Khopa** [comment]
>  Could you maybe propose a better AA units for both sides?

I think some AA systems could be mixed with the frontline units to make CAS a bit more challenging. 
This can be done easily, just by adding the AA units to the pinpoint strike category. (But yeah, eventually they should stay a bit in the back, and not rush toward ennemies like the tanks currently do)

**Frontline AA :** 

| 🔵 | 🔴  | Role | ~Price | Threat | Enabled |
|-----|-----|------|--------|-------|--------|
| -- |  Ural Zu-23 | AAA | 2M | ⭐️⚪️⚪️⚪️⚪️  | 🛑
| Vulcan | Shilka Zsu-23-4 | Radar guided AAA | 6M | ⭐️⭐️⚪️⚪️⚪️ | ✅
| Stinger Manpad  | SA-18 Igla Manpad | Manpad | 4M | ⭐️⭐️⚪️⚪️⚪️  | 🛑  
| -- | SA-9 Strella | APC-mounted Manpad | 8M | ⭐️⭐️⚪️⚪️⚪️ | ✅
| M6 Linebacker | --  | IFV-mounted Manpad | 10M |  ⭐️⭐️⭐️⚪️⚪️| ✅

Then for base defense, we could have :

**Base defense :**

| 🔵 | 🔴  | Role  | ~Price  | Threat | Enabled |
| ----| ---- | ----- | ------- | ------- | ---------- |
| Vulcan | Shilka Zsu-23-4 | Radar guided AAA | 6M | ⭐️⭐️⚪️⚪️⚪️ | ✅ 
| M48 Chapparal | -- | IR SAM | 10M | ⭐️⭐️⭐️⚪️⚪️ | 🛑 
| Avenger | -- | IR SAM | 10M | ⭐️⭐️⭐️⚪️⚪️ | ✅ 
| Roland | SA-8 |  SACLOS SAM | 15M | ⭐️⭐️⭐️⚪️⚪️ | ✅ 
| -- | SA-3 (S-125) ⚠️| Long/Mid Range Radar SAM | 20M | ⭐️⭐️⭐️⚪️⚪️| 🛑 
| -- | SA-19 Tunguska  | Short Range Radar/Optical SAM + AAA | 25M | ⭐️⭐️⭐️⭐️⭐️| ✅ 
| Hawk ⚠️ | SA-6 ⚠️| Long/Mid Range Radar SAM   | 35M | ⭐️⭐️⭐️⚪️⚪️ | 🛑 
| -- | SA-15 Tor | Short/Mid Range Radar SAM | 40M | ⭐️⭐️⭐️⭐️⚪️| 🛑 
| -- | SA-11 Buk ⚠️ | Long Range Radar SAM | 50M | ⭐️⭐️⭐️⭐️⚪️| 🛑 
| Patriot ⚠️ | SA-10 (S-300) ⚠️ | Long Range Radar SAM | 80M | ⭐️⭐️⭐️⭐️⭐️| 🛑 

⚠️ means that multiple units are required to generate a working SAM site. (So hard to integrate right now)
✅ : I think we should have it
🛑 : Not right now, to keep it simple (Eventually later)

**Disclaimer :**
I haven't studied the effectiveness of all systems, i'm not sure whether the values there are entirely relevant. It's just my two cents. 

**Here are some sources :**
* https://forums.eagle.ru/showthread.php?t=84314
* https://wiki.hoggitworld.com/view/Threat_Database

**Comment by shdwp** [comment]
Thanks a lot, I've updated the selection in 1.4.
