### ISSUE TITLE
Feature Request: Combined Arms slots

### ISSUE THREAD

**Issue by Khopa** [shdwp/dcs_liberation#17]
**Feature Request :** Combined Arms slots

When playing DCS in coop, it's always interesting to have someone playing/directing the ground units.

On my dev branch, i added the possibility to add combined arms "tactical commander" slots to the mission. 

It allow taking control of the ground units, or to give them order if you own the Combined Arms module. 
It also allow players to act as GCI/AWACS.

See : https://github.com/Khopa/dcs_liberation/commit/0ffcf5b442d44d6428d8f09e616c34efaf6c1402

![image](https://user-images.githubusercontent.com/2546901/44090836-cce52744-9fcb-11e8-9f93-c5ef3a03aa4c.png)

I'll make a pull request later if you want.

**Comment by shdwp** [comment]
Sure, if you made a PR I'd gladly accept it.

**Comment by Khopa** [comment]
Sorry to be late, i was kind of busy lately, but here is finally the PR : https://github.com/shdwp/dcs_liberation/pull/27
