### ISSUE TITLE
View time of day on the mission before selecting aircraft

### ISSUE THREAD

**Issue by SomethingSimpl** [shdwp/dcs_liberation#19]
Would it be possible to implement a Time of Day for the generated mission to be shown at the aircraft selection screen? I would really love to be able to properly plan (AV-8B for night missions for example) but thats not really possible as you can only find out in game after you start the mission at this point.

**Comment by MaHuJa** [comment]
For anyone looking at this because they ended up with a non-night plane at night, or impossible weather conditions:
It's possible to 'take back' a generated mission by clicking at a base and then back out of the buy screen, rather than fail the mission.

**Comment by wrycu** [comment]
This is done and staged for 1.5.1.  The setup permits displaying weather as well, but I didn't actually implement displaying that yet.

![image](https://user-images.githubusercontent.com/4709746/66981100-a7431580-f067-11e9-8207-78e8c2d9a6ae.png)

**Comment by wrycu** [comment]
Added in 1.5.1.
