### ISSUE TITLE
In-Game Mission Generation from Stennis

### ISSUE THREAD

**Issue by Luftwolfe** [shdwp/dcs_liberation#2]
Mission generates fine, go to play mission, fly to bulls, nothing spawns. There's a lag spike where I think the game is trying to generate the content, but it never does.

**Comment by PatchworkHD** [comment]
What I've posted in the forums about it. 

> Alright, I think I found the issue for why Carrier missions are not spawning the enemy aircraft (I am using 1.12). 
> 
> The "Push trigger" for carrier ops is using the "ALL OF COALITION OUT OF ZONE" Condition. This is not a suitable trigger condition considering that the carrier itself is part of the Blue coalition and will never end up leaving the push zone. This means the flag 1 value is never set properly, so the enemy doesn't spawn.
> 
> In the meantime, I'm manually setting the condition for the push trigger to "ALL OF GROUP OUT OF ZONE" and selecting the player group.

**Comment by shdwp** [comment]
Fixed in recent release.
