### ISSUE TITLE
Possible airstrike objectives - new categories

### ISSUE THREAD

**Issue by SomethingSimpl** [shdwp/dcs_liberation#24]
- **Fuel** - "Warehouses/Tank" + "Warehouses/Tank 2" + "Structures/Fuel tank" + Any unarmed transport/support truck
- **Ammo** - "Warehouses/Ammunition depot" + "Structures/Hangar B" + Any unarmed transport/support truck
- **Comms** - "Structures/TV tower" + "Structures/Comms tower" + + Any command unit + Any transport unit
- **Oil** - "Structures/Pump station" + "Structures/Oil derrick" + "Structures/Oil platform" + Any unarmed transport/support truck
- **Warehouse** - "Warehouses/Warehouse" + "Structures/Hangar A" + Any unarmed transport/support truck
- **FARP** - "Structures/FARP Ammo Storage" + "Structures/FARP Fuel Depot" + "Structures/FARP Command Post" + "Heliports/FARP" + "Heliports/Helipad Single" + Any unarmed transport/support truck + Any command unit
- **FOB** - "Structures/FARP Tent" + "Structures/Barracks armed" + "Structures/Barracks 2" + "Structures/Watch tower armed" + "Structures/Garage small B" + Any ground unit + Any command unit
- **Power** - "Structures/Workshop A" + "Structures/Electric power box" + "Structures/Garage A" + Any unarmed transport/support truck
- **EWR Site** - EWR 1L13 + EWR 55G6 + CP 9S80M1 Sborka
- **Factory** - "Structures/Tech Combine" + "Structures/Tech Hangar A" + "Structures/Boiler-house A" + Any unarmed transport/support truck
- **Trainyard** - "Structures/Repair workshop" + "Structures/Railway station" + "Structures/Locomotive" + "Structures/Coach for cargo" + "Structures/Coach flatbed" + "Structures/Coach a tank blue" + "Structures/Coach for open cargo" + Any unarmed transport/support truck
- **FSB** - Fire support base (artillery) - "Structures/Shelter B" + Any artillery unit (can spawn any artillery unit) + Any unarmed transport/support truck + Any command unit
- **Checkpoint** - "Structures/Outpost" + "Structures/Road outpost" + Any transport/support truck + Any armored vehicle
- **Runway/Hangar parked aircraft** - any type of static enemy aircraft
- **AA** - any type of enemy AA
- **HVT** - any type of enemy infantry? uaz? not sure here..

Also would we be able to consider vehicles a part of the groups? For example field artillery as a part of FSB strike objective or EWR radars as a part of EWR Site objective?

Would it be possible to use live units and not just units from static objects? So that the EWR radars would emit? Or is there a limitation on the strike mission generation?

Would it make sense to put some of the HVT strikes into cities and build some static "civilian" buildings - this could ask for a precision strike and damage done to the "civilian" buildings would count towards failed strike mission? Is this technically and gameplay-wise feasible?

Would we be able to come up with any workaround in regards to runway strikes? Bomb the runway to make it inoperable type of strike? Not sure how would we gauge the damage done though..

Would it be possible to autogen units based on their class? Transport/support, Armored, Command given specific lists of units and then add them into the objectives as seen in the list above?

What do you guys think about the new objectives types?

**Comment by shdwp** [comment]
This is really cool and seems quite fitting!

> Also would we be able to consider vehicles a part of the groups? For example field artillery as a part of FSB strike objective or EWR radars as a part of EWR Site objective?
I think I will make the vehicles simply stick to closest group. Should be simple enough.

> Runway/Hangar parked aircraft - any type of static enemy aircraft
Feels like a tedious enough job to put those one by one.

> AA - any type of enemy AA
If you want to place AA near other objectives (making it part of that group), there should be a separate vehicle marking AA site. Like, placed Zu23 would not count as AA site and just stick to closest group, and Tunguska would form it's own AA site (as in AA site, the strike objective)

> Would it be possible to use live units and not just units from static objects? So that the EWR radars would emit? Or is there a limitation on the strike mission generation?
Yeah, it should be working just fine. I'll simply generate the same exact vehicles for this kind of things.

> Would it make sense to put some of the HVT strikes into cities and build some static "civilian" buildings - this could ask for a precision strike and damage done to the "civilian" buildings would count towards failed strike mission? Is this technically and gameplay-wise feasible?
Too hard to implement ATM.

> Would we be able to come up with any workaround in regards to runway strikes? Bomb the runway to make it inoperable type of strike? Not sure how would we gauge the damage done though..
I don't think there would be a trigger for that, so not at the moment, no.

> Would it be possible to autogen units based on their class? Transport/support, Armored, Command given specific lists of units and then add them into the objectives as seen in the list above?
Should be simple enough, if you provide the lists.

BTW, do you have any progress on the placements itself? Just keep in mind that we'd have to place everything manually (there are templates in the editor, but anyway), so don't make plans that would be too hard to accomplish, ok?

**Comment by SomethingSimpl** [comment]
Ive already reworked half of the southern side that was already done. Ive created a few variations of objectives when dealing with "from the scratch" FARPS, Camps that I reuse as templates. The objectives embedded into scenery have to be created manually in every instance.

**Comment by shdwp** [comment]
Just don't spend too much time on this. And, by any chance - could I take a peek and verify that everything's fine?

**Comment by SomethingSimpl** [comment]
First WIP version of the southern part up to Sukhumi-Babushara, trying to juggle multiple types to keep it varied across the map.

[cau_groundobjects.zip](https://github.com/shdwp/dcs_liberation/files/2398320/cau_groundobjects.zip)

**Comment by shdwp** [comment]
I think I'd rather scrap the current implementation and go for one requiring less manual work.

Thanks for the suggestion tho, I'll keep them in mind when designing the "templates" for the objectives..
