### ISSUE TITLE
Strike mission persistance

### ISSUE THREAD

**Issue by SomethingSimpl** [shdwp/dcs_liberation#26]
Hi,

Are there any plans to make the destroyed objectives of strike missons persist when doing strikes on the same airfield multiple times?

Would it be possible?

**Comment by shdwp** [comment]
You mean the wreckages, right? I have this in dev branch, so it would be on release.

**Comment by SomethingSimpl** [comment]
Yeah, I mean that if we rerun the strike mission I wont have to kill the same targets and they wont count towards the score. So if I manage to kill 10 out of 20 fuel tanks in the Strike 1 I can only target the other untouched 10 in the Strike 2.

**Comment by shdwp** [comment]
Yes, it's how it should be done already. The "objective" will remain until there's at least 1 building standing out of the group, after that it would vanish completely.

**Comment by SomethingSimpl** [comment]
Good, what I noticed though that FRONTLINE CAP missions that spawn the base in as well spawn it untouched after previous Strike missions. The persistence only works in between Strike missions. Other missions spawn the base in untouched. Just a minor gripe though.

**Comment by shdwp** [comment]
Hmm, I'll look into it, maybe I've missed something, thanks.

**Comment by SomethingSimpl** [comment]
It looks like the persistence does not currently work at all. Weve cleared the whole map in one of the strike missions and it still offered us to do it all over again - all of the same objectives ready to be destroyed. Is that how its supposed to be?

Also Ive noticed that there was no "progress" on the frontline in the strategic map upon killing all of the objectives.

**Comment by shdwp** [comment]
Hm, may be a bug. I haven't thoroughly tested it on the dev branch. Will check.
