### ISSUE TITLE
Different difficulty drop-downs for Planes and AA

### ISSUE THREAD

**Issue by SomethingSimpl** [shdwp/dcs_liberation#28]
Hi,

Would it be possible to implement two separate difficulty sliders for Planes and AA? As I find enemy Planes like to cheat in different ways when set to a higher difficulty, but the AA is just completely useless at the same Average difficulty. Thats why I think it would be great to have 2 separate drop-downs so you can set ground units to - Excelent while having planes only set to - Average.

**Comment by shdwp** [comment]
Implemented. Will be in next release.
