### ISSUE TITLE
UI issue not being able to click "ready"

### ISSUE THREAD

**Issue by zbenesch** [shdwp/dcs_liberation#35]
Unfortunately I can't resize the window, so I can't click "let's kick ass!" :( 
![image](https://user-images.githubusercontent.com/31964331/47588859-c7b22580-d967-11e8-9781-f36e84973c04.png)
Any ideas how to make it visible?

**Comment by shdwp** [comment]
Huh. I'll see. For now you should sell some of the units so that the list would get smaller.

Also, what version is that? In 1.4 the scramble list should be divided into two columns.

**Comment by zbenesch** [comment]
It should be 1.4.4.
I can sell stuff? I’ll take a look.
Is it really necessary to list the AG aircraft in the “escort” column?

**Comment by shdwp** [comment]
Closed due to the units screen redesign.
