### ISSUE TITLE
Base attack error

### ISSUE THREAD

**Issue by zbenesch** [shdwp/dcs_liberation#46]
Tried to do a base attack on Sir Abu from Al Dhafra. Got an error (pfa txt below pic).
![image](https://user-images.githubusercontent.com/31964331/47961512-ca1e1a80-e00c-11e8-8d74-9928d4e48e05.png)
[baseattack.txt](https://github.com/shdwp/dcs_liberation/files/2545644/baseattack.txt)

**Comment by shdwp** [comment]
This particular issue will be fixed in the next build (although it's not the only one when it comes to the base attack units placement).
