### ISSUE TITLE
Add Tomcat

### ISSUE THREAD

**Issue by linmar22** [shdwp/dcs_liberation#56]
Fits the scenario perfectly too.

**Comment by shdwp** [comment]
1) pydcs is not updated yet.
2) I'm on a business trip right now so I wouldn't be able to test it

If pydcs gets updated and you can confirm that liberation actually works on the latest version of the DCS I could push out the update without testing tho.

**Comment by linmar22** [comment]
No worries, thought i should at least make a ticket for tracking purposes ;) Might want to hold off on the release until ED fix their events though.
