### ISSUE TITLE
Campaign crash/save corruption

### ISSUE THREAD

**Issue by Rushyo** [shdwp/dcs_liberation#59]
After saving the debrief for a successful Strike/SEAD mission I've twice had Liberation crash and corrupt the save file (the TMP save file is also corrupted).

I'm running the 1.5 RC1 release against the Steam Open Beta branch, flying an F/A-18C Hornet in SP using JDAMs, supported by Tomcats + Harriers.

The error is:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "ui\overviewcanvas.py", line 183, in sdl_thread
  File "ui\overviewcanvas.py", line 252, in draw
  File "ui\overviewcanvas.py", line 312, in draw_map
  File "ui\overviewcanvas.py", line 331, in draw_bases
ValueError: negative radius
```

When I try to restart the application I get "Your save game is either incompatible or was corrupted!"

[Debrief File](https://www.dropbox.com/s/57h1ifrdqo50hdp/last.log?dl=0)
[Campaign save file](https://www.dropbox.com/s/bi1qjhcnzymggqm/liberation_save?dl=0)

**Comment by Rushyo** [comment]
This should be resolved by https://github.com/shdwp/dcs_liberation/pull/58#issue-267307532

**Comment by Czar59** [comment]
Hello, How do I implement the changes in comment 58? I've downloaded the source files and can find the number to change but I don't know how to run the program from the source files. My programming experience is basically none.
