### ISSUE TITLE
Float Division by Zero

### ISSUE THREAD

**Issue by omsktransmash** [shdwp/dcs_liberation#6]
When I finished a frontline attack mission and saved the debriefing as usual, the "wait for debriefing" screen did not move forward to result screen.

I checked the log.txt then I found that there is Float Division by Zero Error, where
```
game/event/frontlineattack.py
Line 33:
attackers_success = (float(alive_attackers) / alive_defenders + 0.01) > self.SUCCESS_FACTOR
```

(sorry didnt keep the log)
It was clear that somehow i eliminated all defending units, including SAM, so alive_defenders maybe zero. Above formula would be 5 / 0 + 0.01 and as python calculates multiply/division first and plus / minus later, hence the error.

1. I changed the line to 
`attackers_success = (float(alive_attackers) / float(alive_defenders + 0.01)) > self.SUCCESS_FACTOR`
but dont know it was your original intention

2. I found the same formula in
```
game/event/frontlineattack.py
game/event/insurgentattack.py
game/event/frontlinepatrol.py
```

all above may potentially generate "Division by Zero" Error, if alive_something is zero

**Comment by shdwp** [comment]
Thanks a lot, I did miss that. Guess that what coding at night does to you. Should be fixed in recent release
