### ISSUE TITLE
Active Maintainers

### ISSUE THREAD

**Issue by JohanAberg** [shdwp/dcs_liberation#65]
This code is a very popular dcs mod, but maintenance seems to suffer lately.
Would the owner be open to share the maintenance and release duty to other developers so that we can maintain a working version out there?
I'm interested in helping out.

**Comment by Czar59** [comment]
I sure hope so! I've been checking frequently as the Value Error has made it unplayable

**Comment by shdwp** [comment]
Sadly I'm stopped playing DCS since VR performance became unbearably bad.

Guess that would be a good idea to get a few maintainers other than myself. I will write up a section on how to prepare build zip file and that should be it.

**Comment by shdwp** [comment]
I've sent out a couple of Collaborators invites.

Development guide was updated to to include short instruction on how to make a build zip. Just make sure to copy the loadouts from previous release zip as per instruction.

**Comment by wrycu** [comment]
@shdwp I'm interested in helping maintain the project (rather than just working on my forked copy.) Can you shoot me an invite?

**Comment by shdwp** [comment]
Sent out an invite for you as well @wrycu

**Comment by wrycu** [comment]
Thanks.

I've created a Discord server so we can discuss things without having to go through Github issues, please feel free to join.

https://discord.gg/bKrtrkJ
