### ISSUE TITLE
F-16 support

### ISSUE THREAD

**Issue by Gromek1982** [shdwp/dcs_liberation#72]
Hello, 

Are you planning to add F-16 as a flyable model ?

**Comment by Khopa** [comment]
Yes. 

We have to update the pydcs framework to include the new F-16C.

I opened an issue there (https://github.com/pydcs/dcs/issues/21), and I might look into this issue myself later.

**Comment by Gromek1982** [comment]
Many thanks Khopa !

**Comment by jayrook** [comment]
Awesome! Can’t wait :)

**Comment by wrycu** [comment]
(This was added in 1.5.1)
