### ISSUE TITLE
Cant play more than one mission in multiplayer

### ISSUE THREAD

**Issue by felixausten** [shdwp/dcs_liberation#75]
After completing one mission on multiplayer and saving the logs, I get this message.

INFO:root:DCS Libration None
INFO:root:Using C:\Users\Felix\Saved Games\DCS as userdata folder
INFO:root:Beslan - BTR-80 12
INFO:root:Beslan - MiG-21Bis 2
INFO:root:Beslan - MiG-23MLD 2
INFO:root:Beslan - F-5E-3 2
INFO:root:Beslan - AJS37 1
INFO:root:Beslan - L-39ZA 1
INFO:root:Beslan - MiG-15bis 1
INFO:root:Beslan - ZSU-23-4 Shilka 1
INFO:root:Nalchik - BTR-80 8
INFO:root:Nalchik - T-55 8
INFO:root:Nalchik - M-2000C 3
INFO:root:Nalchik - MiG-23MLD 3
INFO:root:Nalchik - Su-27 3
INFO:root:Nalchik - Su-25T 1
INFO:root:Nalchik - L-39ZA 1
INFO:root:Nalchik - AJS37 1
INFO:root:Nalchik - ZSU-23-4 Shilka 1
INFO:root:Nalchik - Strela-1 9P31 1
INFO:root:Mozdok - BTR-80 8
INFO:root:Mozdok - T-55 8
INFO:root:Mozdok - M-2000C 3
INFO:root:Mozdok - MiG-23MLD 3
INFO:root:Mozdok - Su-27 3
INFO:root:Mozdok - Su-25T 1
INFO:root:Mozdok - L-39ZA 1
INFO:root:Mozdok - AJS37 1
INFO:root:Mozdok - ZSU-23-4 Shilka 1
INFO:root:Mozdok - Strela-1 9P31 1
INFO:root:Mineralnye - T-90 8
INFO:root:Mineralnye - T-80UD 8
INFO:root:Mineralnye - T-55 8
INFO:root:Mineralnye - MiG-29A 4
INFO:root:Mineralnye - Su-33 4
INFO:root:Mineralnye - Su-27 4
INFO:root:Mineralnye - MiG-29S 4
INFO:root:Mineralnye - Su-25T 2
INFO:root:Mineralnye - Su-34 2
INFO:root:Mineralnye - L-39ZA 2
INFO:root:Mineralnye - Su-25 2
INFO:root:Mineralnye - ZSU-23-4 Shilka 1
INFO:root:Mineralnye - Osa 9A33 ln 1
INFO:root:Mineralnye - Strela-1 9P31 1
INFO:root:Maykop - T-90 9
INFO:root:Maykop - T-80UD 9
INFO:root:Maykop - T-55 9
INFO:root:Maykop - MiG-29A 4
INFO:root:Maykop - Su-33 4
INFO:root:Maykop - Su-27 4
INFO:root:Maykop - MiG-29S 4
INFO:root:Maykop - Su-25T 2
INFO:root:Maykop - Su-34 2
INFO:root:Maykop - L-39ZA 2
INFO:root:Maykop - Su-25 2
INFO:root:Maykop - ZSU-23-4 Shilka 1
INFO:root:Maykop - Osa 9A33 ln 1
INFO:root:Maykop - Strela-1 9P31 1
INFO:root:Kutaisi - BTR-80 12
INFO:root:Kutaisi - MiG-21Bis 2
INFO:root:Kutaisi - MiG-23MLD 2
INFO:root:Kutaisi - F-5E-3 2
INFO:root:Kutaisi - AJS37 1
INFO:root:Kutaisi - L-39ZA 1
INFO:root:Kutaisi - MiG-15bis 1
INFO:root:Kutaisi - ZSU-23-4 Shilka 1
INFO:root:Senaki - BTR-80 12
INFO:root:Senaki - MiG-21Bis 2
INFO:root:Senaki - MiG-23MLD 2
INFO:root:Senaki - F-5E-3 2
INFO:root:Senaki - AJS37 1
INFO:root:Senaki - L-39ZA 1
INFO:root:Senaki - MiG-15bis 1
INFO:root:Senaki - ZSU-23-4 Shilka 1
INFO:root:Kobuleti - BTR-80 8
INFO:root:Kobuleti - T-55 8
INFO:root:Kobuleti - M-2000C 3
INFO:root:Kobuleti - MiG-23MLD 3
INFO:root:Kobuleti - Su-27 3
INFO:root:Kobuleti - Su-25T 1
INFO:root:Kobuleti - L-39ZA 1
INFO:root:Kobuleti - AJS37 1
INFO:root:Kobuleti - ZSU-23-4 Shilka 1
INFO:root:Kobuleti - Strela-1 9P31 1
INFO:root:Batumi - T-90 8
INFO:root:Batumi - T-80UD 8
INFO:root:Batumi - T-55 8
INFO:root:Batumi - MiG-29A 4
INFO:root:Batumi - Su-33 4
INFO:root:Batumi - Su-27 4
INFO:root:Batumi - MiG-29S 4
INFO:root:Batumi - Su-25T 2
INFO:root:Batumi - Su-34 2
INFO:root:Batumi - L-39ZA 2
INFO:root:Batumi - Su-25 2
INFO:root:Batumi - ZSU-23-4 Shilka 1
INFO:root:Batumi - Osa 9A33 ln 1
INFO:root:Batumi - Strela-1 9P31 1
INFO:root:Sukhumi - T-80UD 10
INFO:root:Sukhumi - T-55 10
INFO:root:Sukhumi - MiG-29A 4
INFO:root:Sukhumi - Su-27 4
INFO:root:Sukhumi - MiG-29S 4
INFO:root:Sukhumi - Su-25T 2
INFO:root:Sukhumi - Su-34 2
INFO:root:Sukhumi - Su-25 2
INFO:root:Sukhumi - Osa 9A33 ln 1
INFO:root:Sukhumi - Strela-1 9P31 1
INFO:root:Gudauta - T-80UD 10
INFO:root:Gudauta - T-55 10
INFO:root:Gudauta - MiG-29A 4
INFO:root:Gudauta - Su-27 4
INFO:root:Gudauta - MiG-29S 4
INFO:root:Gudauta - Su-25T 2
INFO:root:Gudauta - Su-34 2
INFO:root:Gudauta - Su-25 2
INFO:root:Gudauta - Osa 9A33 ln 1
INFO:root:Gudauta - Strela-1 9P31 1
INFO:root:Sochi - T-90 9
INFO:root:Sochi - T-80UD 9
INFO:root:Sochi - T-55 9
INFO:root:Sochi - MiG-29A 4
INFO:root:Sochi - Su-33 4
INFO:root:Sochi - Su-27 4
INFO:root:Sochi - MiG-29S 4
INFO:root:Sochi - Su-25T 2
INFO:root:Sochi - Su-34 2
INFO:root:Sochi - L-39ZA 2
INFO:root:Sochi - Su-25 2
INFO:root:Sochi - ZSU-23-4 Shilka 1
INFO:root:Sochi - Osa 9A33 ln 1
INFO:root:Sochi - Strela-1 9P31 1
INFO:root:Gelendzhik - BTR-80 8
INFO:root:Gelendzhik - T-55 8
INFO:root:Gelendzhik - M-2000C 3
INFO:root:Gelendzhik - MiG-23MLD 3
INFO:root:Gelendzhik - Su-27 3
INFO:root:Gelendzhik - Su-25T 1
INFO:root:Gelendzhik - L-39ZA 1
INFO:root:Gelendzhik - AJS37 1
INFO:root:Gelendzhik - ZSU-23-4 Shilka 1
INFO:root:Gelendzhik - Strela-1 9P31 1
INFO:root:Krymsk - T-80UD 10
INFO:root:Krymsk - T-55 10
INFO:root:Krymsk - MiG-29A 4
INFO:root:Krymsk - Su-27 4
INFO:root:Krymsk - MiG-29S 4
INFO:root:Krymsk - Su-25T 2
INFO:root:Krymsk - Su-34 2
INFO:root:Krymsk - Su-25 2
INFO:root:Krymsk - Osa 9A33 ln 1
INFO:root:Krymsk - Strela-1 9P31 1
INFO:root:Anapa - T-90 9
INFO:root:Anapa - T-80UD 9
INFO:root:Anapa - T-55 9
INFO:root:Anapa - MiG-29A 4
INFO:root:Anapa - Su-33 4
INFO:root:Anapa - Su-27 4
INFO:root:Anapa - MiG-29S 4
INFO:root:Anapa - Su-25T 2
INFO:root:Anapa - Su-34 2
INFO:root:Anapa - L-39ZA 2
INFO:root:Anapa - Su-25 2
INFO:root:Anapa - ZSU-23-4 Shilka 1
INFO:root:Anapa - Osa 9A33 ln 1
INFO:root:Anapa - Strela-1 9P31 1
INFO:root:Krasnodar - T-90 9
INFO:root:Krasnodar - T-80UD 9
INFO:root:Krasnodar - T-55 9
INFO:root:Krasnodar - MiG-29A 4
INFO:root:Krasnodar - Su-33 4
INFO:root:Krasnodar - Su-27 4
INFO:root:Krasnodar - MiG-29S 4
INFO:root:Krasnodar - Su-25T 2
INFO:root:Krasnodar - Su-34 2
INFO:root:Krasnodar - L-39ZA 2
INFO:root:Krasnodar - Su-25 2
INFO:root:Krasnodar - ZSU-23-4 Shilka 1
INFO:root:Krasnodar - Osa 9A33 ln 1
INFO:root:Krasnodar - Strela-1 9P31 1
INFO:root:generated ammo for Soganlug
INFO:root:generated aa for Soganlug
INFO:root:generated comms for Soganlug
INFO:root:generated oil for Soganlug
INFO:root:generated fob for Soganlug
INFO:root:generated aa for Soganlug
INFO:root:generated aa for Beslan
INFO:root:generated factory for Beslan
INFO:root:generated farp for Beslan
INFO:root:generated comms for Beslan
INFO:root:generated aa for Beslan
INFO:root:generated fob for Nalchik
INFO:root:generated fob for Nalchik
INFO:root:generated aa for Nalchik
INFO:root:generated farp for Nalchik
INFO:root:generated aa for Nalchik
INFO:root:generated comms for Mozdok
INFO:root:generated ware for Mozdok
INFO:root:generated farp for Mozdok
INFO:root:generated comms for Mozdok
INFO:root:generated power for Mozdok
INFO:root:generated aa for Mozdok
INFO:root:generated factory for Mineralnye
INFO:root:generated fuel for Mineralnye
INFO:root:generated comms for Mineralnye
INFO:root:generated fuel for Mineralnye
INFO:root:generated aa for Mineralnye
INFO:root:generated ware for Maykop
INFO:root:generated farp for Maykop
INFO:root:generated farp for Maykop
INFO:root:generated comms for Maykop
INFO:root:generated aa for Maykop
INFO:root:generated fuel for Kutaisi
INFO:root:generated factory for Kutaisi
INFO:root:generated fuel for Kutaisi
INFO:root:generated factory for Kutaisi
INFO:root:generated aa for Kutaisi
INFO:root:generated ammo for Senaki
INFO:root:generated factory for Senaki
INFO:root:generated factory for Senaki
INFO:root:generated aa for Senaki
INFO:root:generated fuel for Senaki
INFO:root:generated aa for Senaki
INFO:root:generated factory for Kobuleti
INFO:root:generated oil for Kobuleti
INFO:root:generated comms for Kobuleti
INFO:root:generated fob for Kobuleti
INFO:root:generated fuel for Kobuleti
INFO:root:generated aa for Kobuleti
INFO:root:generated oil for Batumi
INFO:root:generated factory for Batumi
INFO:root:generated aa for Batumi
INFO:root:generated ware for Batumi
INFO:root:generated aa for Batumi
INFO:root:generated ammo for Sukhumi
INFO:root:generated ware for Sukhumi
INFO:root:generated fob for Sukhumi
INFO:root:generated factory for Sukhumi
INFO:root:generated comms for Sukhumi
INFO:root:generated aa for Sukhumi
INFO:root:generated ammo for Gudauta
INFO:root:generated ammo for Gudauta
INFO:root:generated aa for Gudauta
INFO:root:generated fuel for Gudauta
INFO:root:generated aa for Gudauta
INFO:root:generated factory for Sochi
INFO:root:generated aa for Sochi
INFO:root:generated comms for Sochi
INFO:root:generated ware for Sochi
INFO:root:generated aa for Sochi
INFO:root:generated oil for Gelendzhik
INFO:root:generated factory for Gelendzhik
INFO:root:generated fob for Gelendzhik
INFO:root:generated ammo for Gelendzhik
INFO:root:generated aa for Gelendzhik
INFO:root:generated comms for Krymsk
INFO:root:generated ware for Krymsk
INFO:root:generated factory for Krymsk
INFO:root:generated fuel for Krymsk
INFO:root:generated aa for Krymsk
INFO:root:generated ware for Anapa
INFO:root:generated factory for Anapa
INFO:root:generated power for Anapa
INFO:root:generated farp for Anapa
INFO:root:generated aa for Anapa
INFO:root:generated power for Krasnodar
INFO:root:generated comms for Krasnodar
INFO:root:generated oil for Krasnodar
INFO:root:generated factory for Krasnodar
INFO:root:generated aa for Krasnodar
INFO:root:Pass turn
INFO:root:<theater.base.Base object at 0x0423D650> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.MiG_23MLD'>: 2}
INFO:root:Generating Strike / SEAD (regular)
INFO:root:airgen: <class 'dcs.planes.FA_18C_hornet'> for 2 at <class 'dcs.terrain.caucasus.Soganlug'>
ERROR:root:Didn't find ground position (Point(-235067.07388582907, 880562.7857448743))!
INFO:root:airgen: <class 'dcs.planes.M_2000C'> for 2 at 3300 at 550
INFO:root:Loaded overridden payload for <class 'dcs.planes.M_2000C'> - Combat Air Patrol for task <class 'dcs.task.CAP'>
INFO:root:airgen: <class 'dcs.planes.MiG_23MLD'> for 0 at 3600 at 550
INFO:root:generated defense object identifier aa|32|7|1 with mission id 6
INFO:root:generated object identifier factory|32|8|1 with mission id 7
INFO:root:generated object identifier factory|32|8|2 with mission id 8
INFO:root:generated object identifier factory|32|8|3 with mission id 9
INFO:root:generated object identifier factory|32|8|4 with mission id 10
INFO:root:generated object identifier farp|32|9|1 with mission id 11
INFO:root:generated object identifier farp|32|9|2 with mission id 12
INFO:root:generated object identifier farp|32|9|3 with mission id 13
INFO:root:generated object identifier farp|32|9|4 with mission id 14
INFO:root:generated object identifier farp|32|9|5 with mission id 15
INFO:root:generated object identifier farp|32|9|6 with mission id 16
INFO:root:generated object identifier farp|32|9|7 with mission id 17
INFO:root:generated object identifier farp|32|9|8 with mission id 18
INFO:root:generated object identifier farp|32|9|9 with mission id 19
INFO:root:generated object identifier comms|32|10|1 with mission id 20
INFO:root:generated defense object identifier aa|32|11|1 with mission id 21
INFO:root:time - 2018-05-25 15:00:00, slot - (9, 18), night skipped - False
INFO:root:generated weather 3
ERROR:root:<class 'PermissionError'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "ui\eventmenu.py", line 217, in start
  File "game\game.py", line 245, in initiate_event
  File "game\event\event.py", line 118, in generate
  File "dcs\mission.py", line 1811, in save
  File "zipfile.py", line 1090, in __init__
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Felix\\Saved Games\\DCS\\Missions\\liberation_nextturn.miz'

**Comment by wrycu** [comment]
This is usually a DCS issue, since the mission is still open and as a result Liberation can't write the new file. Either try loading a different mission in the server before moving to the next within Liberation (not sure if this works), or close DCS, commit to the new mission, and re-open it.
