### ISSUE TITLE
[1.5.1] Mission generation sometimes fails due to weather

### ISSUE THREAD

**Issue by Maeyanie** [shdwp/dcs_liberation#77]
Got an error pop-up when trying to launch a Frontline attack mission.
The window says to send you the text, so, here it is: 
[Window contents](https://gist.github.com/Maeyanie/c51afaa9af1c1877e92731c31c6098a6)

In case they're useful:
[liberation_save.zip](https://github.com/shdwp/dcs_liberation/files/3998605/liberation_save.zip)
[Missions.zip](https://github.com/shdwp/dcs_liberation/files/3998609/Missions.zip)

**Comment by Maeyanie** [comment]
Poking around the code myself, seems like those won't be needed. Looks like it's just that if it rolls clear weather (type 4), it never calls _generate_base_weather(), so never populates the cloud fields, and then [_set_base_weather](https://github.com/shdwp/dcs_liberation/blob/948379d2d3c8ee4833f35b04c4dcc7b129a0dc1f/gen/environmentgen.py#L81) blindly references a field which isn't set and crashes.
Seems like it should be an easy fix, and I should be able to just try again until it rolls a different weather. :)

**Comment by wrycu** [comment]
Yeah, I reworked how those functions worked and didn't do very much testing on them. I'll try and have a fix out this week. In the mean time, regenerating the mission should correct it.

**Comment by wsethbrown** [comment]
I'm having an error with type 3 weather - not sure if they're the same exact issue. Hitting Pass Turn or trying a different mission don't seem to solve it, but the issue revolves around ground troops. Whenever a mission without ground troops is available, it works.

**Comment by wrycu** [comment]
I'll make a new release (1.5.1.1) and try and get #78 and JF-17 support in for it.

**Comment by wsethbrown** [comment]
Not sure if related, but I had what seems to be the same issue but with weather 4.

I've attached the error log below.

[weather4Error.txt](https://github.com/shdwp/dcs_liberation/files/4011932/weather4Error.txt)

**Comment by wrycu** [comment]
That isn't the weather. Try loading a different mission in DCS after completing one (or closing it entirely), as it keeps the mission locked.

From your log:
>PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Seth\\Saved Games\\DCS\\Missions\\liberation_nextturn.miz'

**Comment by wsethbrown** [comment]
Oh I see, I thought just reloading the mission was enough - thanks again for helping me get familiarized with the peculiarities of the campaign :D
