### ISSUE TITLE
[1.5.1] Forced Starting in Air

### ISSUE THREAD

**Issue by wsethbrown** [shdwp/dcs_liberation#78]
Situation:
1. Base Attack from Soganlug to Kutasai
2. Mixed Player and AI Flights

Issues:
1. All players are forced to start in the air

I've attached screenshots of the configuration and mission deployment screens. I don't think I'm doing anything wrong in the settings. This causes us an issue because we often need to edit our loadouts. The F-16, in particular, has a default loadout of no weapons so it's required to land and change weapons just to begin the mission.

![configuration](https://user-images.githubusercontent.com/8193683/71545891-bd6e2b80-295e-11ea-880b-5a18b965ccd9.png)

![setup](https://user-images.githubusercontent.com/8193683/71545892-c2cb7600-295e-11ea-9249-1baf208be656.png)

**Comment by wrycu** [comment]
Can you please include the version you're using and your save file?

**Comment by wsethbrown** [comment]
Version 1.5.1.

Both mission files attached. We never loaded the Quick mission version. I assume it wouldn't fix the issues, but attaching it anyway.

[liberationMissions_AirSpawnBug.zip](https://github.com/shdwp/dcs_liberation/files/4007408/liberationMissions_AirSpawnBug.zip)

**Comment by wrycu** [comment]
Thanks for the quick reply. Can you please include your save game as well?  It's called `liberation_save` and is written to your DCS folder, e.g. `Saved Games\DCS`

**Comment by wsethbrown** [comment]
Unfortunately I overwrote it when I created a new campaign, but will try and replicate it. If so, I'll attach the saved game.

**Comment by wrycu** [comment]
@wsethbrown which aircraft starts in the air? I tried the attached mission file with the Hornet and Tomcat and both started on the ground.

**Comment by wsethbrown** [comment]
All the aircraft spawn in the air. I've attached what I see when I load the mission up.

![airspawn](https://user-images.githubusercontent.com/8193683/71585111-76f60980-2ae3-11ea-99a8-756dd900ad0e.png)

**Comment by wrycu** [comment]
I'm a derp - you're totally correct. That being said, I started a new game, waited until I could perform a base attack, and assigned the same units as you did.  I found that the F-14 started in the air, while the other aircraft started on the ground.  I'll start looking into the issue.
![image](https://user-images.githubusercontent.com/4709746/71595001-defe1d00-2aee-11ea-8e0e-056c724b7cc5.png)

**Comment by wrycu** [comment]
Okay, so the issue is that the airport only has 5 parking spaces and you're committing more than 5 aircraft total (the AI seem to count.) I'll attempt to get some protections against this in place, but for now you can work around the issue by reducing your aircraft count to 5 or less.

**Comment by wsethbrown** [comment]
I thought it might be something like that, but thought if AI were marked to start in the air it wouldn't matter.

Good to know it's a technicality rather than a bug I guess! Thanks for all your work on this. Me and my friends are really loving the progression this mod has that no other dynamic campaign (as far as I know) can offer.

**Comment by wrycu** [comment]
I attempted to start only player aircraft on the ground, but so far as I can tell, grouped aircraft must start at the same location (meaning that the AI takes up parking spots during initial generation). For now, I've added a blocking warning if more aircraft are assigned than the airport has slots for.
![image](https://user-images.githubusercontent.com/4709746/71597875-c0515380-2af9-11ea-918e-28d935aa0306.png)
