### ISSUE TITLE
RuntimeWarning : no module named '_queue'

### ISSUE THREAD

**Issue by 57H07** [shdwp/dcs_liberation#82]
I have Python 3.7 installed.
When i launch  the .bat file, i get this message : "no module named '_queue'"

**Comment by wrycu** [comment]
1. Can you try 1.5.2.1?
2. What's the exact version of python you have installed? (python --version)
3. Has this worked for you in the past, on any version? If so, which version worked?

**Comment by 57H07** [comment]
What's the exact version of python you have installed? (python --version)

- **3.7.5**

Has this worked for you in the past, on any version? If so, which version worked?

- **It's the first time i test it**

Can you try 1.5.2.1?

- **I tried your latest release (1.5.2.2) and i get some warnings but it's seems better.**

![image](https://user-images.githubusercontent.com/17598033/73868170-47f05780-4848-11ea-98aa-4f530ae87297.png)

**Comment by wrycu** [comment]
Awesome. Since it works in 1.5.2.2, I'm closing this out.
