### ISSUE TITLE
Player/Enemy Losses Not Counting

### ISSUE THREAD

**Issue by wsethbrown** [shdwp/dcs_liberation#83]
I'm not sure when it started exactly, but no losses are being counted at the end of a mission. Here are the steps I'm taking:

1. At the end of the mission, hit Escape
2. Press Select Mission
3. Choose the Liberation mission again
4. Once the mission loads, go to C:\Users\NAME\Saved Games\DCS
5. Copy Debrief.txt
6, Paste into C:\Users\NAME\Saved Games\DCS\liberation_debriefings

This causes the Liberation window to show the Operation Result.
However, on two different computers (v1.5.2.1 and v1.5.2
), there are blanks for both Player and Enemy losses.

We've tested this multiple times with no results.

Attached is a screenshot of the results page and two of the debriefs.

![operationFailed](https://user-images.githubusercontent.com/8193683/71705799-0d118480-2daf-11ea-962c-97f984fcd813.png)

[debrief.log](https://github.com/shdwp/dcs_liberation/files/4018054/debrief.log)

[debrief.log](https://github.com/shdwp/dcs_liberation/files/4018065/debrief.log)

**Comment by wrycu** [comment]
![image](https://user-images.githubusercontent.com/4709746/71706572-b0a46a00-2d9a-11ea-9f42-43eaafaf59bd.png)

Spawned a quick single player mission and let myself get shot down and the losses were correctly tracked.  I'll test MP now.

**Comment by wrycu** [comment]
Confirmed it's broken in MP. I'll investigate more.

**Comment by wrycu** [comment]
Released a fix in 1.5.2.2. The problem appears to be a change in how the parsed debrief file is returned - I suspect it's a dependency issue (pyDCS), but I just worked around it.

As a fun side note, I got promoted after running a bunch of missions where all I did was die.
![image](https://user-images.githubusercontent.com/4709746/71708859-e18b9b80-2da8-11ea-89df-eb3186f55adb.png)

**Comment by wsethbrown** [comment]
Didn't even know promotions existed! Thanks for your quick work on all these issues I'm finding >.>
