### ISSUE TITLE
Pending Delivery Broken

### ISSUE THREAD

**Issue by dasrehzockt** [shdwp/dcs_liberation#84]
i have a pending delivery mission to al dhafra, with hueys already located there. when trying to generate the mission i cannot choose an aircraft, only awacs and combined arms slots.
when pressing 'commit' anyways it spits out this:

" ERROR:root:<class 'TypeError'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "ui\eventmenu.py", line 217, in start
TypeError: player_attacking() missing 1 required positional argument: 'flights' "

**Comment by wrycu** [comment]
What version is this happening on, and can you reproduce it with other airports? I was unable to reproduce it on the latest version.

Please provide step-by-step reproduction steps, including the aircraft located at the base, the pending aircraft, and the mission type you're attempting.

**Comment by dasrehzockt** [comment]
i started a new campaign on the persian golf map to do some helo missions. put units to al dhafra and that's all i needed to do to reproduce it. to test it on another base i'd first have to capture one, haven't got that far yet. concerning the version...i have no idea. where would that be displayed? is there some file i could check?
however, i just downloaded this for the very first time on the day i opened this issue, so it is the version that was current on that day.

here is a video that should basically provide any info you need besides the versioning number:

https://www.youtube.com/watch?v=Ms0vaiH4B5E&feature=youtu.be

**Comment by wrycu** [comment]
Thanks for the video, it helped.  You don't actually play delivery missions - they occur automatically after a turn passes.  I've added a check for this so you can't attempt to commit forces to that mission type.

![image](https://user-images.githubusercontent.com/4709746/72392000-c93e4980-36e3-11ea-8669-82ca201c4c86.png)
