### ISSUE TITLE
Could you create a License file please?

### ISSUE THREAD

**Issue by Maj0rCatastrophe** [shdwp/dcs_liberation#86]
So it's clear what you will allow your code to be used for. TY

**Comment by wrycu** [comment]
@shdwp can you comment on this, since you're the actual owner of it?

**Comment by Maj0rCatastrophe** [comment]
You use pydcs which is under the GPL version 3 so I assume this is as well? It would just be nice to be clear about it.

**Comment by wrycu** [comment]
LGPLv3 sounds good to me.

**Comment by Khopa** [comment]
Sounds good for me as well.

**Comment by shdwp** [comment]
Done.
