### ISSUE TITLE
Feature Request: Allow manual selection of DCS folder for missions and debriefs

### ISSUE THREAD

**Issue by HomeFries94** [shdwp/dcs_liberation#9]
Currently, from what I understand, the application defaults to the Saved Games\DCS.Openbeta folder if it sees it, and selects Saved Games\DCS (the stable release) if the Open beta is not present.  I would like to see the ability to manually select the Saved Games\DCS folder, even if Open beta is present.  This would be a major convenience for multiplayer users who coordinate with the stable release, and as a side bonus would allow a second instance of Liberation to run so two campaigns could be simultaneously run on two different builds.

A radio button selection would be ideal, but I would be perfectly happy with an additional argument for init.py (i.e. another argument in start.bat).

**Comment by shdwp** [comment]
Thanks for the suggestion, I think I'd rather add a argument in start.bat for now since properly supporting it would require lots of UI.

**Comment by HomeFries94** [comment]
No problem!

**Comment by shdwp** [comment]
I've added the feature in 1.3.3 release: https://github.com/shdwp/dcs_liberation/wiki/Troubleshooting#i-have-both-dcs-and-dcsopenbeta-user-data-folders-and-want-to-use-dcs
