### ISSUE TITLE
[1.5.2.2] Base Attack - when assigning units it counts vehicles as aircraft

### ISSUE THREAD

**Issue by freeflow66** [shdwp/dcs_liberation#90]
I've been plaing an older version for quite a while with little problem. I decided to load the latest version because you added the JF-17 and the F16 Block C. Unfortunately in this build, everytime I go to do a base attack it counts the vehicles as aircraft and comes back with a message like "You've assigned more aircraft (17) than the airport has parking for (5)!". This is despite the fact that I only have 3 aircraft selected and the other 14 vehicles it is counting as aircraft are in fact tanks.

Text in error report 
"INFO:root:DCS Libration None
INFO:root:Using C:\Users\black\Saved Games\DCS.openbeta as userdata folder
INFO:root:time - 2018-05-25 14:00:00, slot - (8, 16), night skipped - False
INFO:root:generated weather 3
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAP'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAS'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.vehicles.AirDefence'>
INFO:root:time - 2018-05-25 10:00:00, slot - (8, 16), night skipped - False
INFO:root:generated weather 3
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAP'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAS'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.vehicles.AirDefence'>
ERROR:root:<class 'userdata.logging.ShowLogsException'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "ui\window.py", line 137, in report_issue
userdata.logging.ShowLogsException
INFO:root:time - 2018-05-25 11:00:00, slot - (8, 16), night skipped - False
INFO:root:generated weather 3
INFO:root:time - 2018-05-25 11:00:00, slot - (8, 16), night skipped - False
INFO:root:generated weather 3
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAP'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.task.CAS'>
WARNING:root:<theater.base.Base object at 0x0000029D8B103C88>: no units for <class 'dcs.vehicles.AirDefence'>
ERROR:root:<class 'userdata.logging.ShowLogsException'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "ui\window.py", line 137, in report_issue
userdata.logging.ShowLogsException"

**Comment by wrycu** [comment]
Whoops, my bad! Fixed in 02efb98cec98beebfc33240344f1356381b623aa.
