### ISSUE TITLE
[1.5.2.2] Can't save debriefing

### ISSUE THREAD

**Issue by notolos** [shdwp/dcs_liberation#91]
Whenever I save debriefing.log, met this message 
--
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
    self.run()
  File "threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "userdata\debriefing.py", line 207, in _poll_new_debriefing_log
  File "userdata\debriefing.py", line 100, in parse
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 6946: illegal multibyte sequence
--
 I realy want to play second mission...

[debriefing.log](https://github.com/shdwp/dcs_liberation/files/4096807/debriefing.log)

**Comment by wrycu** [comment]
Please post your save, the version you're using, the specific mission you're using, the units committed to the mission.

**Comment by notolos** [comment]
I'm using version 1.5.2.2 / strike mission/ strike flight/ F-16C

Thank you for your reply

[liberation_save.txt](https://github.com/shdwp/dcs_liberation/files/4113713/liberation_save.txt)
[liberation_save_tmp.txt](https://github.com/shdwp/dcs_liberation/files/4113714/liberation_save_tmp.txt)

**Comment by notolos** [comment]
I think I've solved the problem.
I'm sorry to bother you. It's my fault(regarding system language)

**Comment by wrycu** [comment]
No worries. Glad you fixed it.
