### ISSUE TITLE
1.5.2.3 Instructions for Loadout Modification

### ISSUE THREAD

**Issue by marcantonio152** [shdwp/dcs_liberation#94]
Would love to get the new release with some instructions on how to change out the loadout! A friend of mine and I have been playing this, and our biggest frustration is we can't choose our own loadout before flying. With the latest DCS updates, we've been having to shut down the aircraft to rearm... it ends up taking a LONG time to get in the air on this campaign because we want to customize our loadout for each mission.

Please let me know how I can change the loadouts! Thanks!!

**Comment by wrycu** [comment]
@marcantonio152 just to confirm - are the instructions at https://github.com/shdwp/dcs_liberation/wiki/Modding-tutorial not accurate?

Additionally, are there layouts not working? If so, please provide the aircraft and role so we can fix them.
