### ISSUE TITLE
When importing a multiplayer debrief in the current version, friendly destroyed aircraft count as enemy aircraft 

### ISSUE THREAD

**Issue by phntmknight321** [shdwp/dcs_liberation#96]
See title. For example, losing a player owned F-5E3 counts as the enemy losing a MiG-23 once debrief is exported

**Comment by wrycu** [comment]
![image](https://user-images.githubusercontent.com/4709746/80924475-00417500-8d3e-11ea-8993-5ba8c570cbac.png)

Cannot reproduce; closing.
