### ISSUE TITLE
compile after modding

### ISSUE THREAD

**Issue by ITAHawkmoon** [shdwp/dcs_liberation#97]
Ccould we have a guide to compile the source code?
i managed to mod what i wanted to mod but i'm stuck because now i don't know what to do with the code

Many thanks to all and especially the dev behind this

**Comment by wrycu** [comment]
Is there something wrong with the docs at https://github.com/shdwp/dcs_liberation/wiki/Development-guide?

**Comment by ITAHawkmoon** [comment]
i'm having trouble figuring out some of the steps like "./resources/tools/dcs should point to ./submodules/dcs" and "Copy DCS loadout files from release bundle ./resources/payloads (originally they were scattered around DCS folder)"

**Comment by ITAHawkmoon** [comment]
what is in detail the "verify directory links" step?

**Comment by ITAHawkmoon** [comment]
i passed again about 3 hours tring to figured it out but it only create part of the Dist and the only thing i've changed is the db

**Comment by ITAHawkmoon** [comment]
nothing at all?

**Comment by wrycu** [comment]
Removed that reference; we don't use submodules anymore.

Works for me.

```
(venv3_7) C:\Users\wrycu\PycharmProjects\dcs_liberation>python resources\tools\mkrelease.py
version str:1.9.1
```

**Comment by ITAHawkmoon** [comment]
thanks i'll try later

**Comment by ITAHawkmoon** [comment]
eveything went fine

thank you very much
